### PR TITLE
Removal of defamatory content

### PR DESCRIPTION
**Pull request by ethzr**

### CODE REVIEW

**Comment by real2two** [comment]
This is an archive of drama.gg. If you want content removed, we'll only remove content you created, such as posts you made. We won't remove any posts other people made, unless there's everyone in the thread agrees to delete all their posts.

Also, deleting that single file will not get rid of the posts, so make sure to include the files in the `posts` folder as well.

We'll consider adding an opt-out decision easier (instead of manually doing it) in the future, but currently, we're still adding onto the archive.

**Comment by RDevelops** [comment]
> This is an archive of drama.gg. If you want content removed, we'll only remove content you created, such as posts you made. We won't remove any posts other people made, unless there's everyone in the thread agrees to delete all their posts.
> 
> Also, deleting that single file will not get rid of the posts, so make sure to include the files in the `posts` folder as well.
> 
> We'll consider adding an opt-out decision easier (instead of manually doing it) in the future, but currently, we're still adding onto the archive.

I think that there should not be an option of this, to keep this as close to drama.gg as possible - it pretty much just removes the whole point of archiving it if you're going to remove stuff
As they say, what happens on the internet stays on the internet, and you cant get something removed from archive.org simply because your name appears there.

**Comment by real2two** [comment]
@RDevelops Although I'd love to keep an archive where nothing gets deleted: If a user requests to remove their data from the website, I'm pretty sure there's a law stating I have to remove it.

I won't delete an entire thread though _unless everyone in the thread agrees to delete it_, so I'll **only** delete the posts **created by the user** who wants them deleted.

@layerxbt I won't delete this entire thread, but if you want to specifically delete all of your posts and information from the archive, please reply again to this comment stating that you're requesting for data deletion. 

I haven't created a system that would allow me to delete every post created by a user yet, so please expect it to take time if you respond.

EDIT: Also, if you need assistance with deleting data on the archive website, you'll need to contact @SamCoThePuggo instead.

**Comment by RDevelops** [comment]
@real2two The main issues you would have would reside within the GDPR. Users will need a way to delete their own messages (after proving that an account belongs to them, which may be hard, as they can otherwise delete other peoples messages). 

However, I don't think entire posts should be removed regarding integrity. All members of the thread can request for thier messages to be deleted (or the post be "archived" as it was on drama.gg before) rather than fully pruning the thread.

Also, as i said before security issues may occur if you don't enforce some sort of identity verification to edit data.

Edit: I also think instead of completely deleting messages to have something like reddit which either has:
author: username
message: [DELETED]
or 
author: [DELETED]
message: [DELETED]

**Comment by real2two** [comment]
@RDevelops I won't delete entire posts, which I already mentioned above. I'll only delete posts from the user who requests for deletion.

**Review by real2two — CHANGES_REQUESTED** [review]
I won't delete an entire post which has content you didn't create. Also, the posts still exists in the posts folder.

**Pull request closed without merging**
